# ===== Application =====
spring.application.name=projet-club-escalade
server.port=8080
spring.profiles.active=dev

# ===== H2 =====
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ===== JPA / Hibernate =====
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# ===== JSP =====
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp

# ===== Mail (FakeSMTP) =====
spring.mail.host=localhost
spring.mail.port=10025
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false

# ===== Pagination =====
spring.data.web.pageable.default-page-size=20